-- AlterTable
ALTER TABLE "Post" ADD COLUMN "category" TEXT NOT NULL DEFAULT '',
ADD COLUMN "tags" TEXT NOT NULL DEFAULT '[]',
ADD COLUMN "views" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "authorImage" TEXT,
ADD COLUMN "authorRole" TEXT NOT NULL DEFAULT 'Contributing Writer';
