// Subway line routes with station order and terminal information
// This defines the actual path each line takes through the system

export interface LineRoute {
  id: string;
  name: string;
  color: string;
  terminals: {
    north?: string;
    south?: string;
    east?: string;
    west?: string;
  };
  stations: string[]; // Station slugs in order from south to north (or west to east for crosstown lines)
}

export const SUBWAY_LINE_ROUTES: Record<string, LineRoute> = {
  'TEST': {
    id: 'TEST',
    name: 'TEST - Test Line',
    color: '#FF0000',
    terminals: {
      north: 'test-north',
      south: 'test-south'
    },
    stations: [
      '103rd-st',
      '116th-st-columbia-university',
      '137th-st-city-college',
      '145th-st'
    ]
  },
  '1': {
    id: '1',
    name: '1 - Broadway-7th Avenue Local',
    color: '#EE352E',
    terminals: {
      north: 'van-cortlandt-park-242nd-st',
      south: 'south-ferry'
    },
    stations: [
      'south-ferry',
      'cortlandt-st-temporarily-closed',
      'chambers-st',
      'franklin-st',
      'canal-st',
      'houston-st',
      'christopher-st-sheridan-sq',
      '14th-st',
      '18th-st',
      '23rd-st',
      '28th-st',
      '34th-st-penn-station',
      'times-sq-42-st',
      '50th-st',
      '59th-st-columbus-circle',
      '66th-st-lincoln-ctr',
      '72nd-st',
      '79th-st',
      '86th-st',
      '96th-st',
      '103rd-st',
      '110th-st-cathedral-pkwy',
      '116th-st-columbia-university',
      '125th-st',
      '137th-st-city-college',
      '145th-st',
      '157th-st',
      '168th-st',
      '181st-st',
      '191st-st',
      'dyckman-st',
      '207th-st',
      '215th-st',
      'marble-hill-225th-st',
      '231st-st',
      '238th-st',
      'van-cortlandt-park-242nd-st'
    ]
  },
  '4': {
    id: '4',
    name: '4 - Lexington Avenue Express',
    color: '#00933C',
    terminals: {
      north: 'woodlawn',
      south: 'crown-hts-utica-av'
    },
    stations: [
      'crown-heights-utica-av',
      'franklin-av-medgar-evers-college',
      'atlantic-av-barclays-ctr',
      'nevins-st',
      'borough-hall',
      'bowling-green',
      'wall-st',
      'fulton-st',
      'brooklyn-bridge-city-hall',
      '14-st-union-sq',
      'grand-central-42-st',
      '59-st',
      '86-st',
      '125-st',
      '138-st-grand-concourse',
      '149-st-grand-concourse',
      '161-st-yankee-stadium',
      '167-st',
      '170-st',
      'mt-eden-av',
      '176-st',
      'burnside-av',
      '183-st',
      'fordham-rd',
      'kingsbridge-rd',
      'bedford-park-blvd-lehman-college',
      'mosholu-pkwy',
      'woodlawn'
    ]
  },
  '7': {
    id: '7',
    name: '7 - Flushing Local/Express',
    color: '#B933AD',
    terminals: {
      west: '34-st-hudson-yards',
      east: 'flushing-main-st'
    },
    stations: [
      '34-st-hudson-yards',
      'times-sq-42-st',
      '5-av',
      'grand-central-42-st',
      'vernon-blvd-jackson-av',
      'hunters-point-av',
      'court-sq',
      'queensboro-plaza',
      '33-st-rawson-st',
      '40-st-lowery-st',
      '46-st-bliss-st',
      '52-st-lincoln-av',
      '61-st-woodside',
      '69-st',
      '74-st-broadway',
      '82-st-jackson-hts',
      '90-st-elmhurst-av',
      'junction-blvd',
      '103-st-corona-plaza',
      '111-st',
      'mets-willets-point',
      'flushing-main-st'
    ]
  },
  'L': {
    id: 'L',
    name: 'L - 14th Street-Canarsie Local',
    color: '#A7A9AC',
    terminals: {
      west: '14th-st-8th-ave',
      east: 'canarsie-rockaway-pkwy'
    },
    stations: [
      '14th-st-8th-ave',
      '6th-ave',
      '14th-st-union-sq',
      '3rd-ave',
      '1st-ave',
      'bedford-ave',
      'lorimer-st',
      'graham-ave',
      'grand-st',
      'montrose-ave'
    ]
  },
  'N': {
    id: 'N',
    name: 'N - Broadway Express',
    color: '#FCCC0A',
    terminals: {
      north: 'astoria-ditmars-blvd',
      south: 'coney-island-stillwell-av'
    },
    stations: [
      'coney-island-stillwell-av',
      '86-st',
      'av-u',
      'kings-hwy',
      'bay-pkwy',
      '20-av',
      '18-av',
      '8-av',
      'fort-hamilton-pkwy',
      'new-utrecht-av',
      '62-st',
      '36-st',
      'atlantic-av-barclays',
      'union-st',
      'court-st',
      'whitehall-st-south-ferry',
      'rector-st',
      'canal-st',
      '14-st-union-sq',
      '23-st',
      '28-st',
      '34-st-herald-sq',
      'times-sq-42-st',
      '49-st',
      '57-st-7-av',
      '5-av-59-st',
      'lexington-av-59-st',
      'queensboro-plaza',
      '39-av',
      '36-av',
      'broadway',
      '30-av',
      'astoria-blvd',
      'astoria-ditmars-blvd'
    ]
  },
  'Q': {
    id: 'Q',
    name: 'Q - Broadway Express',
    color: '#FCCC0A',
    terminals: {
      north: '96-st',
      south: 'coney-island-stillwell-av'
    },
    stations: [
      'coney-island-stillwell-av',
      'ocean-pkwy',
      'west-8-st-ny-aquarium',
      'brighton-beach',
      'sheepshead-bay',
      'neck-rd',
      'av-u',
      'kings-hwy',
      'av-j',
      'av-h',
      'newkirk-plaza',
      'cortelyou-rd',
      'beverley-rd',
      'church-av',
      'parkside-av',
      'prospect-park',
      '7-av',
      'atlantic-av-barclays',
      'dekalb-av',
      'canal-st',
      '14-st-union-sq',
      '23-st',
      '28-st',
      '34-st-herald-sq',
      'times-sq-42-st',
      '49-st',
      '57-st-7-av',
      'lexington-av-59-st',
      '72-st',
      '86-st',
      '96-st'
    ]
  },
  'A': {
    id: 'A',
    name: 'A - 8th Avenue Express',
    color: '#0039A6',
    terminals: {
      north: 'inwood-207-st',
      south: 'far-rockaway-mott-av', // Main terminal
      west: 'ozone-park-lefferts-blvd', // Lefferts branch
      east: 'rockaway-park-beach-116-st' // Rockaway Park branch
    },
    stations: [
      // Main route from Manhattan to Brooklyn to Queens
      'inwood-207-st',
      'dyckman-st',
      '190-st',
      '181-st',
      '175-st',
      '168-st',
      '145-st',
      '125-st',
      '59-st-columbus-circle',
      '42-st-port-authority',
      '34-st-penn-station',
      '14-st',
      'w-4-st-washington-sq',
      'canal-st',
      'chambers-st',
      'fulton-st',
      'high-st',
      'jay-st-metrotech',
      'hoyt-schermerhorn',
      'nostrand-av',
      'utica-av',
      'broadway-junction',
      'euclid-av',
      'grant-av',
      '80-st',
      '88-st',
      'rockaway-blvd',
      '104-st',
      '111-st',
      'ozone-park-lefferts-blvd',
      // Far Rockaway branch
      'howard-beach-jfk-airport',
      'aqueduct-racetrack',
      'aqueduct-north-conduit-av',
      'broad-channel',
      'beach-67-st',
      'beach-60-st',
      'beach-44-st',
      'beach-36-st',
      'beach-25-st',
      'far-rockaway-mott-av',
      // Rockaway Park branch
      'beach-90-st',
      'beach-98-st',
      'beach-105-st',
      'rockaway-park-beach-116-st'
    ]
  },
  'E': {
    id: 'E',
    name: 'E - 8th Avenue Local',
    color: '#0039A6',
    terminals: {
      north: 'jamaica-center-parsons-archer',
      south: 'world-trade-center'
    },
    stations: [
      'world-trade-center',
      'chambers-st',
      'canal-st',
      'spring-st',
      'west-4-st',
      '14-st',
      '23-st',
      '34-st-penn-station',
      '42-st-port-authority',
      '50-st',
      '7-av',
      '5-av-53-st',
      'lexington-av-53-st',
      'court-sq-23-st',
      'queens-plaza',
      '36-st',
      'steinway-st',
      '46-st',
      'northern-blvd',
      '65-st',
      'roosevelt-av',
      'elmhurst-av',
      'grand-av-newtown',
      'woodhaven-blvd',
      '63-dr-rego-park',
      '67-av',
      'forest-hills-71-av',
      '75-av',
      'kew-gardens-union-tpke',
      'briarwood',
      'sutphin-blvd',
      'parsons-blvd',
      '169-st',
      'jamaica-179-st',
      'jamaica-center-parsons-archer'
    ]
  },
  '2': {
    id: '2',
    name: '2 - 7th Avenue Express',
    color: '#EE352E',
    terminals: {
      north: 'wakefield-241-st',
      south: 'flatbush-av-brooklyn-college'
    },
    stations: [
      'flatbush-av-brooklyn-college',
      'newkirk-av',
      'beverly-rd',
      'church-av',
      'winthrop-st',
      'sterling-st',
      'president-st',
      'botanic-garden',
      'franklin-av',
      'eastern-pkwy-brooklyn-museum',
      'grand-army-plaza',
      'bergen-st',
      'atlantic-av-barclays-ctr',
      'nevins-st',
      'hoyt-st',
      'borough-hall',
      'clark-st',
      'wall-st',
      'fulton-st',
      'park-place',
      'chambers-st',
      '14-st',
      '34-st-penn-station',
      'times-sq-42-st',
      '72-st',
      '96-st',
      '110-st-central-park-north',
      '116-st',
      '125-st',
      '135-st',
      '149-st-grand-concourse',
      '3-av-149-st',
      'jackson-av',
      'prospect-av',
      'intervale-av',
      'simpson-st',
      'freeman-st',
      '174-st',
      'west-farms-sq-e-tremont-av',
      'e-180-st',
      'bronx-park-east',
      'pelham-pkwy',
      'allerton-av',
      'burke-av',
      'gun-hill-rd',
      '219-st',
      '225-st',
      '233-st',
      'nereid-av',
      'wakefield-241-st'
    ]
  },
  '3': {
    id: '3',
    name: '3 - 7th Avenue Express',
    color: '#EE352E',
    terminals: {
      north: 'harlem-148-st',
      south: 'new-lots-av'
    },
    stations: [
      'new-lots-av',
      'van-siclen-av',
      'pennsylvania-av',
      'junius-st',
      'rockaway-av',
      'saratoga-av',
      'sutter-av-rutland-rd',
      'crown-hts-utica-av',
      'kingston-av',
      'nostrand-av',
      'botanic-garden',
      'eastern-pkwy-brooklyn-museum',
      'grand-army-plaza',
      'bergen-st',
      'atlantic-av-barclays-ctr',
      'nevins-st',
      'hoyt-st',
      'court-st',
      'clark-st',
      'wall-st',
      'fulton-st',
      'chambers-st',
      '14-st',
      '34-st-penn-station',
      'times-sq-42-st',
      '72-st',
      '96-st',
      '110-st-malcolm-x-plaza',
      '116-st',
      '125-st',
      '135-st',
      '145-st',
      'harlem-148-st'
    ]
  },
  '5': {
    id: '5',
    name: '5 - Lexington Avenue Express',
    color: '#00933C',
    terminals: {
      north: 'eastchester-dyre-av',
      south: 'flatbush-av-brooklyn-college'
    },
    stations: [
      'flatbush-av-brooklyn-college',
      'newkirk-av-little-haiti',
      'beverly-rd',
      'church-av',
      'winthrop-st',
      'sterling-st',
      'president-st-medgar-evers-college',
      'franklin-av-medgar-evers-college',
      'atlantic-av-barclays-ctr',
      'nevins-st',
      'borough-hall',
      'bowling-green',
      'wall-st',
      'fulton-st',
      'brooklyn-bridge-city-hall',
      '14-st-union-sq',
      'grand-central-42-st',
      '59-st',
      '86-st',
      '125-st',
      '138-st-grand-concourse',
      '149-st-grand-concourse',
      '3-av-149-st',
      'jackson-av',
      'prospect-av',
      'intervale-av',
      'simpson-st',
      'freeman-st',
      '174-st',
      'west-farms-sq-e-tremont-av',
      'e-180-st',
      'morris-park',
      'pelham-pkwy',
      'gun-hill-rd',
      'baychester-av',
      'eastchester-dyre-av'
    ]
  },
  '6': {
    id: '6',
    name: '6 - Lexington Avenue Local',
    color: '#00933C',
    terminals: {
      north: 'pelham-bay-park',
      south: 'brooklyn-bridge-city-hall'
    },
    stations: [
      'brooklyn-bridge-city-hall',
      'canal-st',
      'spring-st',
      'bleecker-st',
      'astor-pl',
      '8-st-nyu',
      '14-st-union-sq',
      '23-st',
      '28-st',
      '33-st',
      'grand-central-42-st',
      '51-st',
      '59-st',
      '68-st-hunter-college',
      '77-st',
      '86-st',
      '96-st',
      '103-st',
      '110-st',
      '116-st',
      '125-st',
      '138-st-grand-concourse',
      'brook-av',
      'cypress-av',
      'e-143-st-st-marys-st',
      'e-149-st',
      'longwood-av',
      'hunts-point-av',
      'whitlock-av',
      'elder-av',
      'morrison-av-soundview',
      'st-lawrence-av',
      'parkchester',
      'castle-hill-av',
      'zerega-av',
      'westchester-sq-e-tremont-av',
      'middletown-rd',
      'buhre-av',
      'pelham-bay-park'
    ]
  },
  'B': {
    id: 'B',
    name: 'B - 6th Avenue Express',
    color: '#FF6319',
    terminals: {
      north: 'bedford-park-blvd',
      south: 'brighton-beach'
    },
    stations: [
      'brighton-beach',
      'sheepshead-bay',
      'kings-hwy',
      'newkirk-plaza',
      'church-av',
      'prospect-park',
      '7-av',
      'atlantic-av-barclays-ctr',
      'dekalb-av',
      'grand-st',
      'broadway-lafayette-st',
      'w-4-st-wash-sq',
      '34-st-herald-sq',
      '42-st-bryant-pk',
      '47-50-sts-rockefeller-ctr',
      '59-st-columbus-circle',
      '72-st',
      '81-st-museum-of-natural-history',
      '86-st',
      '96-st',
      '103-st',
      'cathedral-pkwy-110-st',
      '116-st',
      '125-st',
      '135-st',
      '145-st',
      '155-st',
      '161-st-yankee-stadium',
      '167-st',
      '170-st',
      '174-175-sts',
      'tremont-av',
      '182-183-sts',
      'kingsbridge-rd',
      'fordham-rd',
      'bedford-park-blvd'
    ]
  },
  'C': {
    id: 'C',
    name: 'C - 8th Avenue Local',
    color: '#0039A6',
    terminals: {
      north: '168-st',
      south: 'euclid-av'
    },
    stations: [
      'euclid-av',
      'shepherd-av',
      'van-siclen-av',
      'liberty-av',
      'broadway-junction',
      'ralph-av',
      'rockaway-av',
      'utica-av',
      'nostrand-av',
      'kingston-throop-avs',
      'franklin-av',
      'clinton-washington-avs',
      'lafayette-av',
      'hoyt-schermerhorn-sts',
      'jay-st-metrotech',
      'high-st',
      'fulton-st',
      'chambers-st',
      'canal-st',
      'spring-st',
      'west-4-st',
      '14-st',
      '23-st',
      '34-st-penn-station',
      '42-st-port-authority',
      '50-st',
      '59-st-columbus-circle',
      '72-st',
      '81-st-museum-of-natural-history',
      '86-st',
      '96-st',
      '103-st',
      '110-st-cathedral-pkwy',
      '116-st',
      '125-st',
      '135-st',
      '145-st',
      '155-st',
      '163-st-amsterdam-av',
      '168-st'
    ]
  },
  'D': {
    id: 'D',
    name: 'D - 6th Avenue Express',
    color: '#FF6319',
    terminals: {
      north: 'norwood-205-st',
      south: 'coney-island-stillwell-av'
    },
    stations: [
      'coney-island-stillwell-av',
      'bay-50-st',
      '25-av',
      'bay-pkwy',
      '20-av',
      '18-av',
      '79-st',
      '71-st',
      '62-st',
      '55-st',
      '50-st',
      'fort-hamilton-pkwy',
      '9-av',
      '36-st',
      'atlantic-av-barclays-ctr',
      'dekalb-av',
      'canal-st',
      'grand-st',
      'broadway-lafayette-st',
      'west-4-st-washington-sq',
      '14-st',
      '23-st',
      '34-st-herald-sq',
      '42-st-bryant-park',
      '47-50-sts-rockefeller-ctr',
      '7-av',
      '57-st-7-av',
      '59-st-columbus-circle',
      '125-st',
      '145-st',
      '155-st',
      '161-st-yankee-stadium',
      '167-st',
      '170-st',
      '174-175-sts',
      'tremont-av',
      '182-183-sts',
      'fordham-rd',
      'kingsbridge-rd',
      'bedford-park-blvd',
      'norwood-205-st'
    ]
  },
  'F': {
    id: 'F',
    name: 'F - 6th Avenue Local',
    color: '#FF6319',
    terminals: {
      north: 'jamaica-179-st',
      south: 'coney-island-stillwell-av'
    },
    stations: [
      'coney-island-stillwell-av',
      'west-8-st-ny-aquarium',
      'neptune-av',
      'av-x',
      'av-u',
      'kings-hwy',
      'av-p',
      'av-n',
      'bay-pkwy',
      'av-i',
      '18-av',
      'ditmas-av',
      'church-av',
      'fort-hamilton-pkwy',
      '15-st-prospect-park',
      '4-av-9-st',
      '7-av',
      'bergen-st',
      'carroll-st',
      'smith-9-sts',
      'york-st',
      'jay-st-metrotech',
      'delancey-st-essex-st',
      'east-broadway',
      '2-av',
      'broadway-lafayette-st',
      'west-4-st-washington-sq',
      '14-st',
      '23-st',
      '34-st-herald-sq',
      '42-st-bryant-park',
      '47-50-sts-rockefeller-ctr',
      '57-st',
      'lexington-av-63-st',
      'roosevelt-island',
      '21-st-queensbridge',
      'queens-plaza',
      '36-st',
      'steinway-st',
      '46-st',
      'northern-blvd',
      '65-st',
      'roosevelt-av',
      'elmhurst-av',
      'grand-av-newtown',
      'woodhaven-blvd',
      '63-dr-rego-park',
      '67-av',
      'forest-hills-71-av',
      '75-av',
      'kew-gardens-union-tpke',
      'briarwood',
      'sutphin-blvd',
      'parsons-blvd',
      '169-st',
      'jamaica-179-st'
    ]
  },
  'G': {
    id: 'G',
    name: 'G - Brooklyn-Queens Crosstown',
    color: '#6CBE45',
    terminals: {
      north: 'court-sq',
      south: 'church-av'
    },
    stations: [
      'church-av',
      'fort-hamilton-pkwy',
      '15-st-prospect-park',
      '4-av-9-st',
      '7-av',
      'bergen-st',
      'carroll-st',
      'smith-9-sts',
      'hoyt-schermerhorn-sts',
      'fulton-st',
      'clinton-washington-avs',
      'classon-av',
      'bedford-nostrand-avs',
      'myrtle-willoughby-avs',
      'flushing-av',
      'broadway',
      'metropolitan-av',
      'nassau-av',
      'greenpoint-av',
      '21-st',
      'court-sq'
    ]
  },
  'J': {
    id: 'J',
    name: 'J - Nassau Street Local',
    color: '#996633',
    terminals: {
      north: 'jamaica-center-parsons-archer',
      south: 'broad-st'
    },
    stations: [
      'broad-st',
      'fulton-st',
      'chambers-st',
      'canal-st',
      'bowery',
      'delancey-st-essex-st',
      'marcy-av',
      'hewes-st',
      'lorimer-st',
      'flushing-av',
      'myrtle-av',
      'kosciuszko-st',
      'gates-av',
      'halsey-st',
      'chauncey-st',
      'broadway-junction',
      'alabama-av',
      'van-siclen-av',
      'cleveland-st',
      'norwood-av',
      'crescent-st',
      'cypress-hills',
      '75-st-elderts-ln',
      '85-st-forest-pkwy',
      'woodhaven-blvd',
      '104-st',
      '111-st',
      '121-st',
      'sutphin-blvd-archer-av-jfk-airport',
      'jamaica-center-parsons-archer'
    ]
  },
  'M': {
    id: 'M',
    name: 'M - 6th Avenue Local',
    color: '#FF6319',
    terminals: {
      north: 'forest-hills-71-av',
      south: 'middle-village-metropolitan-av'
    },
    stations: [
      'middle-village-metropolitan-av',
      'fresh-pond-rd',
      'forest-av',
      'seneca-av',
      'myrtle-wyckoff-avs',
      'knickerbocker-av',
      'central-av',
      'jefferson-st',
      'dekalb-av',
      'wyckoff-av',
      'flushing-av',
      'lorimer-st',
      'hewes-st',
      'marcy-av',
      'delancey-st-essex-st',
      'bowery',
      'canal-st',
      'chambers-st',
      'fulton-st',
      'broad-st',
      'court-st',
      'lawrence-st',
      'jay-st-metrotech',
      'dekalb-av',
      'canal-st',
      'broadway-lafayette-st',
      'west-4-st',
      '14-st',
      '23-st',
      '34-st-herald-sq',
      '42-st-bryant-park',
      '47-50-sts-rockefeller-ctr',
      '5-av-53-st',
      'lexington-av-53-st',
      'court-sq-23-st',
      'queens-plaza',
      '36-st',
      'steinway-st',
      '46-st',
      'northern-blvd',
      '65-st',
      'roosevelt-av',
      'elmhurst-av',
      'grand-av-newtown',
      'woodhaven-blvd',
      '63-dr-rego-park',
      '67-av',
      'forest-hills-71-av'
    ]
  },
  'R': {
    id: 'R',
    name: 'R - Broadway Local',
    color: '#FCCC0A',
    terminals: {
      north: 'forest-hills-71-av',
      south: 'bay-ridge-95-st'
    },
    stations: [
      'bay-ridge-95-st',
      '86-st',
      '77-st',
      'bay-ridge-av',
      '59-st',
      '53-st',
      '45-st',
      '36-st',
      '25-st',
      'prospect-av',
      '4-av-9-st',
      'union-st',
      'atlantic-av-barclays-ctr',
      'court-st',
      'jay-st-metrotech',
      'whitehall-st-south-ferry',
      'rector-st',
      'cortlandt-st',
      'city-hall',
      'canal-st',
      'prince-st',
      '8-st-nyu',
      '14-st-union-sq',
      '23-st',
      '28-st',
      '34-st-herald-sq',
      'times-sq-42-st',
      '49-st',
      '57-st-7-av',
      '5-av-59-st',
      'lexington-av-59-st',
      'queens-plaza',
      '36-st',
      'steinway-st',
      '46-st',
      'northern-blvd',
      '65-st',
      'roosevelt-av',
      'elmhurst-av',
      'grand-av-newtown',
      'woodhaven-blvd',
      '63-dr-rego-park',
      '67-av',
      'forest-hills-71-av'
    ]
  },
  'S': {
    id: 'S',
    name: 'S - 42nd Street Shuttle',
    color: '#808183',
    terminals: {
      west: 'times-sq-42-st',
      east: 'grand-central-42-st'
    },
    stations: [
      'times-sq-42-st',
      'grand-central-42-st'
    ]
  },
  'W': {
    id: 'W',
    name: 'W - Broadway Local',
    color: '#FCCC0A',
    terminals: {
      north: 'astoria-ditmars-blvd',
      south: 'whitehall-st-south-ferry'
    },
    stations: [
      'whitehall-st-south-ferry',
      'rector-st',
      'cortlandt-st',
      'city-hall',
      'canal-st',
      'prince-st',
      '8-st-nyu',
      '14-st-union-sq',
      '23-st',
      '28-st',
      '34-st-herald-sq',
      'times-sq-42-st',
      '49-st',
      '57-st-7-av',
      '5-av-59-st',
      'lexington-av-59-st',
      'queensboro-plaza',
      '39-av',
      '36-av',
      'broadway',
      '30-av',
      'astoria-blvd',
      'astoria-ditmars-blvd'
    ]
  },
  'Z': {
    id: 'Z',
    name: 'Z - Nassau Street Express',
    color: '#996633',
    terminals: {
      north: 'jamaica-center-parsons-archer',
      south: 'broad-st'
    },
    stations: [
      'broad-st',
      'fulton-st',
      'chambers-st',
      'canal-st',
      'bowery',
      'delancey-st-essex-st',
      'marcy-av',
      'myrtle-av',
      'broadway-junction',
      'sutphin-blvd-archer-av-jfk-airport',
      'jamaica-center-parsons-archer'
    ]
  }
};

// Helper function to get line route by ID
export function getLineRoute(lineId: string): LineRoute | undefined {
  return SUBWAY_LINE_ROUTES[lineId];
}

// Helper function to get all line IDs
export function getAllLineIds(): string[] {
  return Object.keys(SUBWAY_LINE_ROUTES);
}

// Helper function to check if a station is on a line
export function isStationOnLine(stationSlug: string, lineId: string): boolean {
  const route = SUBWAY_LINE_ROUTES[lineId];
  return route ? route.stations.includes(stationSlug) : false;
}